### ISSUE TITLE
Can't shutdown

### ISSUE THREAD

**Issue by Cyl3el2Cleal2** [lgs3137/MR_S1-macOS#25]
Install on Real MSI-PS42
When shutdown it will boot again!

**Comment by lgs3137** [comment]
I am sorry that I don't have a PS42 real machine, but I have already flashed the BIOS and EC firmware of the PS42 8RB. This EFI is running very well on my machine.
First of all, I need to confirm whether your model is PS42 8RB series? Have you replaced the official wireless card? And the current version of macOS?
BTW, i suggest that you can first try to boot into the BIOS settings to restore the default configuration, then close the secure boot, enter the macOS rebuild cache and restart, and then enter the macOS test shutdown to resolve.
```
sudo kextcache -i /
```

**Comment by Cyl3el2Cleal2** [comment]
My model is PS42 8RB Intel 8250U with HD620 and replace AC3168 with DW1820A.
But I just reinstall OS after panic while installing the upgrade 1.4.5 to 1.4.6 
Now I'm using your EFI it work well! but not test all function.
I notice the touchpad work with some gesture and keyboard shortcut work very well (FN + key).
Can OS X run with great battery life same as windows ?
I use better battery mod on windows it run very long time ( about 7 - 9 hour).

**Comment by Cyl3el2Cleal2** [comment]
Oh I forget to ask you about touchpad.
When I boot windows from clover bootloader my touchpad can't use.
I need to sleep and wake again for make touchpad work.
How to fix that problem. (I can use when boot from Microsoft EFI I mean set it as first boot order in bios)
Thank you.

**Comment by lgs3137** [comment]
About Hackintosh battery life can be optimized by the more CPU frequency can refer to: https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/one-key-cpufriend generate different ```CPUFriendDataProvider.kext``` to optimize as much as possible battery life.

The touchpad cannot be used under Windows, you only need to delete the touchpad driver in the Windows Device Manager, and then reinstall the officially downloaded touchpad driver to solve it. (You need to manually add the touchpad driver certificate to the system trust root certificate area).
http://download.msi.com/nb_drivers/tp/tp_Synaptics_v19_5_10_132__C__x64__Win10__Signed__msi_PUWP_RS4_19.5.10.132_0xaff984ba.zip

BTW, shutdown becomes restart caused by DW1820A and now it has different problems on different models,Including upgrade or installation macOS causing kernel panic.This should mainly be caused by the Bluetooth device of the USB interface.So if this happens, try using the latest EFI to remove ```SSDT-USB.aml``` and then use the attached ```SSDT-USB_noBT.aml``` to block USB Bluetooth.

[SSDT-USB_noBT.aml.zip](https://github.com/lgs3137/MR_S1-macOS/files/3538094/SSDT-USB_noBT.aml.zip)

**Comment by Cyl3el2Cleal2** [comment]
I already try that touchpad driver it still not fix my issues.
I need to sleep and wake windows every time to use touchpad BTW It work with no synaptics driver but touchpad gesture is really nice to use.
Do you have a next suggestion for fixing this?
Thank you.

**Comment by lgs3137** [comment]
[touchpad_synaptics_19.5.31.11_w1064_Win64.zip](https://github.com/lgs3137/MR_S1-macOS/files/3539089/touchpad_synaptics_19.5.31.11_w1064_Win64.zip)

You can try this version of the touchpad driver.
Shutdown, remove AC power, press the "rest" of the back the hole or reinstall the Windows system

**Comment by Cyl3el2Cleal2** [comment]
Ummmm. It does not work again...
I used your EFI for a while it work fine but Right click is not great sometime it miss and slow response but left click and tap nice work.
Do you have this problem? I have been using voodoo kext before Right click work fine but no gesture.

**Comment by lgs3137** [comment]
I almost don't need a touchpad, because the touchpad of this machine is too small. I just tested it and found that there is a delay or invalid response to the two-finger touch. I need to open the debug log and check the VoodooPS2 recent commit troubleshooting issues.
